//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymProgWebApiDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillMuscleGroup
    {
        public int Id { get; set; }
        public int DrillId { get; set; }
        public int MuscleGroupId { get; set; }
    
        public virtual Drill Drill { get; set; }
        public virtual MuscleGroup MuscleGroup { get; set; }
    }
}
