//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymProgWebApiDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymProgDBEntities : DbContext
    {
        public GymProgDBEntities()
            : base("name=GymProgDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DrillMuscleGroup> DrillMuscleGroups { get; set; }
        public virtual DbSet<Drill> Drills { get; set; }
        public virtual DbSet<MuscleGroup> MuscleGroups { get; set; }
        public virtual DbSet<ProgramDrill> ProgramDrills { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Set> Sets { get; set; }
        public virtual DbSet<UserProgram> UserPrograms { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
